<div class="jumbotron">
	<div class="container">
		<h1><?php echo $texts['ui_privacy_policy']; ?></h1>
		<div>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vitae mi sed metus dapibus fringilla quis at massa. Pellentesque quis mauris vel purus congue pretium eu efficitur sem. Aliquam eu tempor leo. Aliquam erat volutpat. Donec at commodo lorem. Suspendisse tempus eros quis lectus commodo, a blandit ex rutrum. Suspendisse sodales nibh pellentesque, condimentum lorem sodales, rutrum quam. Aenean placerat imperdiet odio vel ultrices. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec ante arcu, imperdiet ut consequat mollis, scelerisque ut arcu. Vestibulum in libero justo. Maecenas dictum quam vulputate nunc imperdiet, eget mollis quam fermentum. Nullam euismod hendrerit ex, non vestibulum erat consectetur sed. In laoreet mattis ultricies.</p>
			<p>Aenean non imperdiet leo, quis blandit nisl. Nunc cursus rhoncus dolor, a fermentum purus elementum non. Fusce at massa ac ante dapibus pulvinar id ut orci. Integer facilisis cursus sagittis. Mauris iaculis vel arcu facilisis vestibulum. Etiam vel nisl sit amet urna gravida convallis vel auctor erat. Donec in dui mattis, scelerisque magna ac, aliquet urna. Integer eleifend lectus vitae mi iaculis, in elementum felis volutpat. Nullam quis placerat sapien. Mauris id turpis vitae justo tincidunt mattis. Vestibulum vel odio dolor. Nam tempor gravida libero, faucibus tempor dolor malesuada ut. Quisque a purus finibus enim finibus condimentum. Fusce in ultricies purus. Proin molestie pellentesque eros ut pharetra. Suspendisse tortor massa, sagittis vel faucibus sit amet, mattis sit amet risus.</p>				<p>Duis ut turpis gravida, volutpat ex ac, blandit dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec at vestibulum lorem. Fusce ac dolor tristique, fermentum orci sed, commodo odio. Cras imperdiet massa tortor, ut rutrum diam interdum in. Curabitur venenatis, quam in consequat pharetra, risus massa aliquam sem, ut commodo massa arcu viverra nunc. Nullam et aliquet felis. Curabitur vitae neque a purus mollis egestas. Donec dui risus, cursus vitae ante ac, accumsan eleifend nulla. Sed maximus ultrices neque, non maximus sem consectetur sit amet. Mauris eget blandit ipsum. Aliquam ultrices nulla vel diam molestie, in rhoncus velit malesuada. Aliquam id faucibus ante.</p>
			<p>Etiam scelerisque dui nec arcu molestie rhoncus. Etiam justo risus, varius at sollicitudin vitae, laoreet vitae diam. Ut dui erat, rhoncus non pharetra eget, tincidunt quis lacus. Pellentesque iaculis turpis ac nisi ultrices scelerisque. Aenean varius dignissim condimentum. Donec viverra semper orci vel pellentesque. Sed blandit rutrum sem.</p>
			<p>Nunc nisi magna, aliquam id mollis ac, ornare id arcu. Curabitur nisi tellus, egestas eu congue et, placerat vitae enim. Aliquam porta mollis dolor vel bibendum. Donec vel erat tortor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis at pellentesque turpis. Pellentesque volutpat risus vitae diam commodo, at vestibulum justo placerat. Etiam eget justo eu velit sodales luctus. In in convallis augue. Suspendisse accumsan sit amet nunc vitae tincidunt. Nulla facilisi. Proin fringilla tincidunt tincidunt. Donec ac ultrices lorem. Nunc turpis dui, euismod ac nunc in, vehicula blandit magna.</p>
		</div>
	</div>
</div>